gaelscout/gaelscout/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teams/', include('teaminfo.urls')),
    path('', include('sri.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gaelscout/sri/urls.py
from django.urls import path
from . import views

app_name = 'sri'

urlpatterns = [
    path('', views.index, name='index'),
    # path('<str:team_number>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<str:team_number>/analyze/', views.analyze, name='results'),
    # # ex: /polls/5/vote/
    # path('<str:team_number>/vote/', views.vote, name='vote'),
]

gaelscout/teaminfo/urls.py
from django.urls import path
from . import views

app_name = 'teaminfo'

urlpatterns = [
    path('', views.index, name='index'),
    path('division/', views.division, name='division'),
    path('<str:team_number>/', views.detail, name='detail'),
    path('<str:team_number>/vote/', views.vote, name='vote'),
]

gaelscout/sri/models.py
from django.db import models

# Create your models here.

gaelscout/teaminfo/models.py
from django.db import models
import numpy as np
import pandas as pd
import pickle
# Create your models here.
class worldsTeams(models.Model):
    names = models.CharField(max_length=200)
    events = models.CharField(max_length=200)
    ranks = models.DecimalField(max_digits=10, decimal_places=2)
    wlts = models.CharField(max_length=200)
    wpsps = models.CharField(max_length=200)
    mscores = models.DecimalField(max_digits=10, decimal_places=2)
    oprs = models.DecimalField(max_digits=10, decimal_places=2)
    def __str__(self):
        return self.team_number
# data = pd.read_pickle('static/divisiondata/teamList.pkl')
# for i in data:
#     w = worldsTeams(names=)
#     w.save

class Teams(models.Model):
    team_number = models.CharField(max_length=200)
    team_opr = models.DecimalField(max_digits=10, decimal_places=2)
    team_mscore = models.DecimalField(max_digits=10, decimal_places=2)
    team_opr_quantile = models.DecimalField(max_digits=10, decimal_places=2)
    team_mscore_quantile = models.DecimalField(max_digits=10, decimal_places=2)
    # pub_date = models.DateTimeField('date published')
    def __str__(self):
            return self.team_number
    class Meta:
        ordering = ["-team_opr_quantile"]
    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


# class Choice(models.Model):
#     question = models.ForeignKey(Team, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
#     def __str__(self):
#             return self.question_text

gaelscout/sri/views.py
from django.shortcuts import render
# from matplotlib import pyplot as plt
# import seaborn as sns
import numpy as np
import pandas as pd
from django.shortcuts import render
from django.http import HttpResponse, Http404
from teaminfo.models import Teams
from django.template import loader

# Create your views here.
def index(request):
    # sridata = pd.read_pickle("teamfuncs/sridata.pkl")
    # snsplot = sns.lmplot(x='OPR', y='Max Score', data=sridata, fit_reg=True)
    # plt.show()
    # return render(request, 'sri/index.html', {"plot": snsplot})
    return render(request, 'sri/index.html')

gaelscout/teaminfo/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from teaminfo.models import Teams
from django.template import loader
import operator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# from django.db.models
# Create your views here.
def index(request):
    # data=pd.read_pickle("teamfuncs/sridata.pkl")
    # for num, opr, mscr in zip(data["Team Number"], data["OPR"], data["Max Score"]):
    #      opr_per = stats.percentileofscore(data["OPR"], opr)
    #      mscr_per = stats.percentileofscore(data["Max Score"], mscr)
    #      t = Teams(team_number=num, team_opr=opr, team_mscore=mscr, team_opr_quantile=opr_per, team_mscore_quantile=mscr_per)
    #      t.save()

    # http://materializecss.com/pagination.html
    team_list = Teams.objects.all()

    paginator = Paginator(team_list, 25) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        team_list = paginator.get_page(page)
    except PageNotAnInteger:
        team_list = paginator.page(1)
    except EmptyPage:
        team_list = paginator.page(paginator.num_pages)
    context = {
        'team_list': team_list,
    }

    if request.method == 'POST':
        filter = request.POST.get('filter')
        context['filter'] = filter
        return render(request, 'teaminfo/index.html', context)


    return render(request, 'teaminfo/index.html', context)



def detail(request, team_number):
    try:
        team_num = Teams.objects.get(team_number=team_number)
    except Teams.DoesNotExist:
        return render(request, 'teaminfo/404.html')
    opr = team_num.team_opr
    mscore = team_num.team_mscore
    opr_per = team_num.team_opr_quantile
    mscore_per = team_num.team_mscore_quantile

    context = {
        'team_number': team_number,
        'opr': opr,
        'mscore': mscore,
        'opr_per': opr_per,
        'mscore_per': mscore_per,
    }
    return render(request, 'teaminfo/detail.html', context)

def division(request):
    context = {
        'data' : 'data',
    }
    return render(request, 'teaminfo/division.html', context)

    # context = {
    #     'this':'that',
    # }
    # return render(request, 'teaminfo/division.html', context)

def vote(request):
    return HttpResponse("You're voting on team")

gaelscout/sri/templates/sri/index.html
<!DOCTYPE html>
<html>

<head>
  <title>GaelScout Index</title>
  <link rel="shortcut icon" href="../../../static/gael.ico" type="image/x-icon">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i" rel="stylesheet">
  <link rel = "stylesheet" type = "text/css" href = "../../../static/main.css" />
</head>

<body>
  <nav>
    <div class="nav-wrapper red">
      <div class="container">
        <a class="brand-logo" href="{% url 'sri:index' %}">
          GAELSCOUT</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">Home</a></li>
        <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">SRI</a></li>
        <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Team Index</a></li>
        <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Predictions</a></li>
        <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:division' %}">Division</a></li>
      </ul>
    </div>
      <div class="nav-wrapper">
    </div>
  </nav>
  <div class="container" style="min-height:450px">
    <br>

    <h4>{% load static %}
<img src="{% static "gael.svg" %}" alt="My image" style="max-width: 200px; float: right;"/>Welcome to the GaelScout ITZ Team Index, made by team 5327B.</h4>


  </div>

  <footer class="page-footer red">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Who are we?</h5>
        <p class="grey-text text-lighten-4">We are an experienced and completely student-run high school club whose members work on both real life engineering projects and participate in the VEX Robotics Competition.

Around 6 years old now, our club takes pride in its members’ teamwork and problem solving skills. We also heavily emphasize the engineering design process and ensure that all members have knowledge of such engineering aspects through our yearly seminars.

</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">More About Us</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://vexdb.io/teams/view/5327B" target="_blank">VexDB</a></li>
          <li><a class="grey-text text-lighten-3" href="https://dhsrobotics.com" target="_blank">Our Website</a></li>
          <li><a class="grey-text text-lighten-3" href="https://github.com/GaelForceRoboticsClub/VRC-Team-5327B" target="_blank">Robot Code</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright red darken-4">
    <div class="container">
    © 2018 Anish Kachinthaya
    <a class="grey-text text-lighten-4 right" href="https://github.com/anishk23733" target="_blank">Github</a>
    </div>
  </div>
</footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</body>

</html>

gaelscout/teaminfo/templates/teaminfo/detail.html
<!DOCTYPE html>

<html>
  <head>
    <title>In The Zone GaelScout Index</title>
    <link rel="shortcut icon" href="../../../static/gael.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i" rel="stylesheet">
    <link rel = "stylesheet" type = "text/css" href = "../../../static/main.css" />
  </head>
  <body>
    <nav>
      <div class="nav-wrapper red">
        <div class="container">
          <a class="brand-logo" href="{% url 'sri:index' %}">
            GAELSCOUT</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">Home</a></li>

          <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">SRI</a></li>
          <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Team Index</a></li>
          <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Predictions</a></li>
          <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:division' %}">Division</a></li>
        </ul>
      </div>
        <div class="nav-wrapper">
      </div>
    </nav>

    <div class="container" style="min-height:450px">
      <!-- {% load static %}
        <img src="{% static "admin/img/gael.svg" %}"> -->
    <h1>{{team_number}}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if team_number %}
      <p>You are looking at team {{team_number}}.</p>
      <p>Average OPR: {{opr}}.</p>
      <p>Average Max Score: {{mscore}}.</p>
      <p>OPR Percentile: {{opr_per}}%.</p>
      <p>Max Score Percentile: {{mscore_per}}%.</p>
    {% else %}
        <p>No teams are available.</p>
    {% endif %}

    {% load collect_team %}
    {% with data=data|collect:team_number %}
    {% for chunk in data %}
    <p>{{chunk}}</p>
    {% endfor %}
    {% endwith %}

  </div>
  <footer class="page-footer red">
    <div class="footer-copyright red darken-4">
      <div class="container">
      © 2018 Anish Kachinthaya
      <a class="grey-text text-lighten-4 right" href="https://github.com/anishk23733" target="_blank">Github</a>
      </div>
    </div>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

  </body>
</html>

gaelscout/teaminfo/templates/teaminfo/division.html
<!DOCTYPE html>
<html>
  <head>
    <title>Engineering Division</title>
    <link rel="shortcut icon" href="../../../static/gael.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i" rel="stylesheet">
    <link rel = "stylesheet" type = "text/css" href = "../../../static/main.css" />
  </head>
  <body>
    <nav>
      <div class="nav-wrapper red">
        <div class="container">
          <a class="brand-logo" href="{% url 'sri:index' %}">
            GAELSCOUT</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">Home</a></li>
          <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">SRI</a></li>
          <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Team Index</a></li>
          <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Predictions</a></li>
          <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:division' %}">Division</a></li>
        </ul>
      </div>
        <div class="nav-wrapper">
      </div>
    </nav>

    <div class="container" style="min-height:450px">
      <br>
    <h2>Worlds Engineering Division</h2>
</div>
    <footer class="page-footer red">
    <div class="footer-copyright red darken-4">
      <div class="container">
      © 2018 Anish Kachinthaya
      <a class="grey-text text-lighten-4 right" href="https://github.com/anishk23733" target="_blank">Github</a>
      </div>
    </div>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

  </body>
</html>

gaelscout/teaminfo/templates/teaminfo/index.html
<!DOCTYPE html>

<html>

<head>
  <title>Team Index</title>
  <link rel="shortcut icon" href="../../../static/gael.ico" type="image/x-icon">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i" rel="stylesheet">
  <link rel = "stylesheet" type = "text/css" href = "../../../static/main.css" />

</head>

<body>
  <nav>
    <div class="nav-wrapper red">
      <div class="container">
        <a class="brand-logo" href="{% url 'sri:index' %}">
          GAELSCOUT</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">Home</a></li>
        <li ><a class = "waves-effect waves-light" href="{% url 'sri:index' %}">SRI</a></li>
        <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Team Index</a></li>
        <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:index' %}">Predictions</a></li>
        <li><a class = "waves-effect waves-light" href="{% url 'teaminfo:division' %}">Division</a></li>
      </ul>
    </div>
      <div class="nav-wrapper">
    </div>
  </nav>


  <div class="container">
    <h1><i>In The Zone</i> Team Index</h1>

  <!-- <div style="display: inline-block;">
    <h7>Filters:</h7>
    <form method="POST" class="white-text waves-effect waves-light btn red lighten-1">{% csrf_token %}
      <select name = "filter">
      <option value="by_opr+">OPR++</option>
      </select>
      <input type="submit"  value="OPR +:-"/>
    </form>
    <form method="POST" class="white-text waves-effect waves-light btn red lighten-1">{% csrf_token %}
      <select name = "filter">
      <option value="by_opr-">OPR--</option>
      </select>
      <input type="submit"  value="OPR -:+"/>
    </form>
    <form method="POST" class="white-text waves-effect waves-light btn red lighten-1">{% csrf_token %}
      <select name = "filter">
      <option value="by_mscore+">Max Score++</option>
      </select>
      <input type="submit"  value="Max Score +:-"/>
    </form>
    <form method="POST" class="white-text waves-effect waves-light btn red lighten-1">{% csrf_token %}
      <select name = "filter">
      <option value="by_mscore-">Max Score--</option>
      </select>
      <input type="submit"  value="Max Score -:+"/>
    </form>
  </div>
{% if filter == "by_opr+" %}
{% regroup team_list by team_mscore as team_list %}
{% endif %} -->
    <ul class="pagination">
      {% if team_list.has_previous %}
      <li class="waves-effect"><a href="?page=1">First</a></li>
      <li class="waves-effect"><a href="?page={{ team_list.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}
      <li class="current">
        <a>
          Page
          {{ team_list.number }}
           of
           {{ team_list.paginator.num_pages }}
        </a>
      </li>
      {% if team_list.has_next %}
      <li class="waves-effect"><a href="?page={{ team_list.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
      <li class="waves-effect"><a href="?page={{ team_list.paginator.num_pages }}">Last</a></li>
      {% endif %}
    </ul>

    <table>
      <tr>
        <th>Team Number</th>
        <th>OPR</th>
        <th>Percentile</th>
        <th>Max Score</th>
        <th>Percentile</th>
      </tr>
      {% if team_list %} {% for team in team_list %}
      <tr>
        <td><a href="{% url 'teaminfo:detail' team %}">{{team}}</a></td>
        <td>{{team.team_opr}}</td>
        <td>{{team.team_opr_quantile}}%</td>
        <td>{{team.team_mscore}}</td>
        <td>{{team.team_mscore_quantile}}%</td>
      </tr>
      {% endfor %} {% else %}
      <p>No teams are available.</p>
      {% endif %}
    </table>


    <ul class="pagination">
      {% if team_list.has_previous %}
      <li class="waves-effect"><a href="?page=1">First</a></li>
      <li class="waves-effect"><a href="?page={{ team_list.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
      {% endif %}
      <li class="current">
        <a>
          Page
          {{ team_list.number }}
           of
           {{ team_list.paginator.num_pages }}
        </a>
      </li>
      {% if team_list.has_next %}
      <li class="waves-effect"><a href="?page={{ team_list.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
      <li class="waves-effect"><a href="?page={{ team_list.paginator.num_pages }}">Last</a></li>
      {% endif %}
    </ul>

    <br>
  </div>


  <footer class="page-footer red">
    <div class="footer-copyright red darken-4">
      <div class="container">
        © 2018 Anish Kachinthaya
        <a class="grey-text text-lighten-4 right" href="https://github.com/anishk23733" target="_blank">Github</a>
      </div>
    </div>
  </footer>
  <script>
  var elem = document.querySelector('.dropdown-trigger');
var instance = M.Dropdown.init(elem, options);

  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

</body>

</html>